blog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/users', 'UserController@index')->name('users.index');

Route::get('/user/create', 'UserController@create')->name('users.create')->middleware('auth');
Route::post('/user/store', 'UserController@store')->name('users.store')->middleware('auth');

Route::get('/user/{id}', 'UserController@show')->name('users.show');
Route::get('/user/{id}/edit', 'UserController@edit')->name('users.edit')->middleware('auth');
Route::put('/user/{id}/update', 'UserController@update')->name('users.update')->middleware('auth');
Route::delete('/user/{id}/delete', 'UserController@delete')->name('users.delete')->middleware('auth');

Route::get('/user/{id}/tasks/{task_id}', 'UserController@showTask')->name('users.showTask');

Route::get('todo/completed', 'todoController@indexCompleted')->name('todo.indexCompleted');
Route::resource('todo', 'toDoController');
Route::post('todo/{id}/mark-as-completed', 'todoController@markAsCompleted')->name('todo.complete');

Route::resource('comment', 'CommentController');

blog/app/Http/Controllers/toDoController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use App\Http\Requests\StoreBlogPost;
use App\ToDoItem;
use App\User;
use Illuminate\Http\Request;

class toDoController extends Controller {
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index( Request $request ) {

		$order = "DESC";
		if ( $request->has( 'order' ) ) {
			$order = $request->input( 'order' );
		}

		$todoItems = ToDoItem::orderBy( 'created_at', $order )
							 ->get();

		$users = User::all();


		if ( $order == 'ASC' ) {
			$order = "DESC";
		} else {
			$order = "ASC";
		}


		return view( 'todo.index', [
			"todoItems" => $todoItems,
			"order" => $order,
			"users" => $users
		] );
	}

	public function indexCompleted( Request $request ) {
		$order = "DESC";
		if ( $request->has( 'order' ) ) {
			$order = $request->input( 'order' );
		}

		$todoItems = ToDoItem::where( [ [ 'status', 1 ], [ 'id', '<', 10 ] ] )
							 ->orWhere( 'status', 1 )
							 ->orderBy( 'created_at', $order )
							 ->get();


		$users = User::all();

		if ( $order == 'ASC' ) {
			$order = "DESC";
		} else {
			$order = "ASC";
		}


		return view( 'todo.index', [
			"todoItems" => $todoItems,
			"order" => $order,
			"users" => $users
		] );
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		//
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function store( StoreBlogPost $request ) {

		/* Patikriname savo uzklausa */
		$request->validated();

		// jei validatorius neatitiko taisykliu, tai sita dalis nebevykdoma

		//
		$todoItem          = new ToDoItem();
		$todoItem->title   = $request->input( 'title' );
		$todoItem->user_id = $request->input( 'user_id' );

		$todoItem->save();

		$request->session()->flash( 'message', 'Task was created successfuly!' );

		return redirect()->back();
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function show( $id ) {
		//
		$item = ToDoItem::find( $id );

		return view( 'todo.show', [ "item" => $item ] );
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit( $id ) {
		//
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function update( Request $request, $id ) {
		//

		$validatedData = $request->validate( [
			'title' => 'required|max:5',
			'user_id' => 'exists:users,id',
		] );
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function destroy( $id ) {
		//
		$todoItem = ToDoItem::find( $id );

		/*foreach($todoItem->comments as $comment) {
			$comment->delete();
		}*/

		if ( $todoItem->status == 1 ) {
			$todoItem->delete();
		}

		session()->flash( 'message', 'Task was deleted successfuly!' );
		session()->flash( 'message-class', 'alert-danger' );


		return redirect()->route( 'todo.index' );
	}

	public function markAsCompleted( $id ) {
		$todoItem         = ToDoItem::find( $id );
		$todoItem->status = 1;
		$todoItem->save();

		session()->flash( 'message', 'Task was completed successfuly!' );
		session()->flash( 'message-class', 'alert-success' );


		return redirect()->route( 'todo.index' );
	}
}

blog/resources/views/todo/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Todo list</h1>
        <a href="{{ route('todo.index') }}">
            View all
        </a>
        <a href="{{ route('todo.indexCompleted') }}">
            View completed
        </a>
        {{-- Includinu savo todo sukurimo forma--}}
        @include('todo.components.create')

        <table class="table table-striped">
            <thead>
            <tr>
                <th>Task title</th>
                <th>Task user</th>
                <th>

                    <a href="?order={{ $order }}">
                        Task date
                    </a>

                </th>
                <th>
                    Complete
                </th>
                <th>Delete</th>
            </tr>
            </thead>

            @foreach($todoItems as $item)
                <tr>
                    <td>
                        @if($item->status == 1)
                            <div style="text-decoration: line-through">
                                <a href="{{ route('todo.show', [$item->id]) }}">
                                    {{ $item->title }}
                                </a>

                            </div>
                        @else
                            <a href="{{ route('todo.show', [$item->id]) }}">
                                {{ $item->title }}
                            </a>
                        @endif
                    </td>
                    <td>
                        @isset( $item->user)
                            <a href="{{ route('users.show', [$item->user->id]) }}">
                                {{ $item->user->name }}
                            </a>
                        @endisset

                    </td>
                    <td>
                        {{ $item->created_at }}
                    </td>
                    <td>
                        @if($item->status == 0)
                            <form method="post" action="{{ route('todo.complete', [$item->id]) }}">
                                @csrf
                                <input type="submit" value="Complete" class="btn btn-success">
                            </form>
                        @endif
                    </td>
                    <td>
                        @if($item->status == 1)
                            <form method="post" action="{{ route('todo.destroy', [$item->id]) }}">
                                @csrf
                                @method('delete')
                                <input type="submit" value="X" class="btn btn-danger">
                            </form>
                        @endif

                    </td>
                </tr>
            @endforeach
        </table>

    </div>
@endsection

blog/resources/views/todo/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h1>{{ $item->title }}</h1>

                {{-- Patikrinu ar item turi userio objekto sarysi--}}
                @isset($item->user)
                    <div>
                        Assigned to: {{ $item->user->name }}
                    </div>
                    <div>
                        User email: {{ $item->user->email }}
                    </div>
                @endisset

                <div class="comments mt-3">

                    @include('todo.components.comments-list')

                    <h3>Add a comment</h3>
                    @include('todo.components.comment-form')
                </div>

            </div>
            <div class="col-md-4">
                <h3>Task actions</h3>
                @if($item->status == 0)
                    <form method="post" action="{{ route('todo.complete', [$item->id]) }}">
                        @csrf
                        <input type="submit" value="Complete" class="btn btn-success">
                    </form>
                @endif

                @if($item->status == 1)
                    <form method="post" action="{{ route('todo.destroy', [$item->id]) }}">
                        @csrf
                        @method('delete')
                        <input type="submit" value="Delete" class="btn btn-danger">
                    </form>
                @endif
            </div>
        </div>
    </div>
@endsection