blog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/users', 'UserController@index')->name('users.index');

Route::get('/user/create', 'UserController@create')->name('users.create')->middleware('auth');
Route::post('/user/store', 'UserController@store')->name('users.store')->middleware('auth');

Route::get('/user/{id}', 'UserController@show')->name('users.show');
Route::get('/user/{id}/edit', 'UserController@edit')->name('users.edit')->middleware('auth');
Route::put('/user/{id}/update', 'UserController@update')->name('users.update')->middleware('auth');
Route::delete('/user/{id}/delete', 'UserController@delete')->name('users.delete')->middleware('auth');

Route::get('/user/{id}/tasks/{task_id}', 'UserController@showTask')->name('users.showTask');

Route::get('todo/completed', 'todoController@indexCompleted')->name('todo.indexCompleted');
Route::resource('todo', 'toDoController');
Route::post('todo/{id}/mark-as-completed', 'todoController@markAsCompleted')->name('todo.complete');

Route::resource('comment', 'CommentController');

blog/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                BTA
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->

                {{-- Patikriname ar vartotojas prisijunges--}}
                @guest
                    Login
                @else
                    Labas {{ Auth::user()->name }}s
                @endguest
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('users.index') }}">
                            Users
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('todo.index') }}">
                            Todo list
                        </a>
                    </li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        <div class="container">
            @if(Session::has('message'))
                @if(Session::has('message-class'))
                    <div class="alert {{ Session::get('message-class') }}">
                        {{ Session::get('message') }}
                    </div>
                @else
                    <div class="alert alert-info">
                        {{ Session::get('message') }}
                    </div>
                @endif
            @endif
        </div>

        @yield('content')
    </main>
</div>
</body>
</html>

blog/resources/views/layouts/geras.blade.php
<html>

<head>
    <title>Labas</title>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

<body>
<h1>Geriausias puslapis pasaulyje</h1>
<div class="container">
        <div class="row">
            <div class="col-sm-8">
                @yield('turinys')
            </div>

            <div class="col-sm-4">
                @yield('sidebar')
            </div>
        </div>
</div>

Cia yra foteris
</body>

</html>