blog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/users', 'UserController@index')->name('users.index');

Route::get('/user/create', 'UserController@create')->name('users.create')->middleware('auth');
Route::post('/user/store', 'UserController@store')->name('users.store')->middleware('auth');

Route::get('/user/{id}', 'UserController@show')->name('users.show');
Route::get('/user/{id}/edit', 'UserController@edit')->name('users.edit')->middleware('auth');
Route::put('/user/{id}/update', 'UserController@update')->name('users.update')->middleware('auth');
Route::delete('/user/{id}/delete', 'UserController@delete')->name('users.delete')->middleware('auth');

Route::get('/user/{id}/tasks/{task_id}', 'UserController@showTask')->name('users.showTask');

Route::get('todo/completed', 'todoController@indexCompleted')->name('todo.indexCompleted');
Route::resource('todo', 'toDoController');
Route::post('todo/{id}/mark-as-completed', 'todoController@markAsCompleted')->name('todo.complete');

Route::resource('comment', 'CommentController');

blog/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function todoItems() {
    	return $this->hasMany('App\ToDoItem', 'user_id', 'id');
	}

	public function comments() {
		return $this->hasMany('App\Comment', 'user_id', 'id');
	}

	public function todoItemsUndone() {
    	return ToDoItem::where('user_id', $this->id)->where('status', 0);
	}

	public function todoItemsDone() {
		return ToDoItem::where('user_id', $this->id)->where('status', 1)->get();
	}
}

blog/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserRequest;
use App\ToDoItem;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;


class UserController extends Controller {
	//

	public function index() {

		$users = User::all();

		$usersCount = User::count(); // grazina visu useriu kieki

		return view( 'users.index', [ 'users' => $users, 'usersCount' => $usersCount ] );
	}

	public function show( $id ) {
		$user = User::find( $id );

		return view( 'users.show', [ 'user' => $user ] );
	}

	public function edit( $id ) {

		$user = User::find( $id );

		return view( 'users.edit', [ 'user' => $user ] );
	}

	public function update( UserRequest $request, $id ) {
		$user = User::find( $id );


		$user->name  = $_POST['name'];
		$user->name  = $request->input( 'name' );
		$user->email = $request->input( 'email' );

		if($request->hasFile('avatar')) {
			$extension = $request->file('avatar')->getClientOriginalExtension();

			//Storage::delete($user->avatar);
			$path = $request->file('avatar')->storeAs(
				'public/avatars', $request->user()->id . '.' . $extension
			);
			$user->avatar = $path;
		}

		// issaugome informaciija duombazeje
		$user->save();

		return redirect()->route( 'users.index' );
	}

	public function create() {


		return view( 'users.create' );
	}

	public function store( UserRequest $request ) {

		$user = new User();
		if ( isset( $request->name ) ) {
			$user->name = $request->input( 'name' );
		} else {
			return redirect()->route( 'users.create' );
		}

		$user->email    = $request->email;

		$user->password = Hash::make( $request->input( 'password' ) );

		$user->save();

		$request->session()->flash('message', 'User was created successfuly!');

		return redirect()->route( 'users.index' );
	}

	public function delete(Request $request, $id) {
		$user = User::find($id);
		$user->delete();

		$request->session()->flash('message', 'User was deleted successfuly!');


		return redirect()->route( 'users.index');
	}

	public function showTask($userId, $taskId) {
		$user = User::find($userId);
		$task = ToDoItem::find($taskId);

		return view('users.task', ['user'=> $user, 'task' => $task]);
	}
}

blog/resources/views/users/create.blade.php
@extends('layouts.app')


@section('content')
    <div class="container">
        <h1>
            Vartotojo kurimas
        </h1>

        <form method="post" action="{{ route('users.store') }}">

            {{ csrf_field() }}

            <div class="form-group">
                <label>Vartotojo vardas</label>
                <input required type="text" name="name" class="form-control" value="">
            </div>
            <div class="form-group">
                <label>El.pastas</label>
                <input required type="email" name="email" class="form-control" value="">
            </div>

            <div class="form-group">
                <label>El.pastas</label>
                <input required type="password" name="password" class="form-control" value="">
            </div>


            <input type="submit" class="btn btn-primary">
        </form>
    </div>

@endsection

blog/resources/views/users/edit.blade.php
@extends('layouts.app')


@section('content')
    <div class="container">
        <h1>
            Redaguojate vartotoja: {{ $user->name }}
        </h1>

        <form method="post" action="{{ route('users.update', [$user->id]) }}" enctype="multipart/form-data">

            {{ csrf_field() }}

            {{ method_field('put') }}

            <div class="form-group">
                <input type="text" name="name" class="form-control" value="{{ $user->name }}">
            </div>
            <div class="form-group">
                <input type="email" name="email" class="form-control" value="{{ $user->email }}">
            </div>

            <div class="form-group">
                <input type="file" name="avatar" class="form-control" />
            </div>


            <input type="submit" class="btn btn-primary">
        </form>
    </div>

@endsection

blog/resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h1>Users ( {{ $usersCount }} )</h1>

            </div>

            <div class="col-md-4">
                @guest
                    {{-- Tu esi svecias tau nerodomas sukurimo mygtukas --}}
                @else
                    <a href="{{ route('users.create') }}" class="btn btn-success">
                        Create user
                    </a>
                @endguest

            </div>
        </div>

        <table class="table">
            <thead>
            <tr>
                <th>ID</th>
                <th>Email</th>
                <th>Name</th>
                <th>Tasks Count</th>
                <th>Delete</th>
            </tr>
            </thead>
            @foreach($users as $user)
                <tr>
                    <td>{{ $user->id }}</td>
                    <td>
                        <a href="/user/{{ $user->id }}">
                            {{ $user->email }}
                        </a>
                    </td>
                    <td>
                        <a href="{{ route('users.show', [$user->id]) }}">
                            {{ $user->name }}
                        </a>
                    </td>

                    <td>
                        {{ $user->todoItemsUndone()->count() }}
                    </td>

                    <td>
                        <form method="post" action="{{ route('users.delete', [$user->id]) }}">
                            @csrf
                            {{ method_field('delete') }}
                            <input type="submit" value="X" class="btn btn-danger">
                        </form>
                    </td>
                </tr>
            @endforeach
        </table>
    </div>
@endsection

blog/resources/views/users/show.blade.php
@extends('layouts.app')


@section('content')
    <div class="container">

        <div class="row">
            <div class="col-md-8">
                <h1>
                    Vartotojas: {{ $user->name }}
                </h1>

                <ul>
                    <li>ID {{ $user->id }}</li>
                    <li>Email: {{ $user->email }}</li>
                    <li>Registracijos data: {{ $user->created_at }}</li>
                </ul>
            </div>

            <div class="col-md-4">
                <div class="avatar">
                    <img src="{{ Storage::url($user->avatar) }}" style="width: 100%;" />
                </div>
                <h3>Vartotojo nustatymai</h3>
                <a class="btn btn-info text-white" href="{{ route('users.edit', [$user->id]) }}">
                    Redaguoti vartotoja
                </a>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <h3>User tasks to be done: {{ $user->todoItemsUndone()->count() }}</h3>
                <ul>
                    @foreach($user->todoItemsUndone()->get() as $item)
                        @if($item->status == 0)
                            <li>
                                {{ $item->title }}
                            </li>
                        @endif
                    @endforeach
                </ul>
            </div>

            <div class="col-md-6">
                <h3>User tasks done:</h3>
                <ul>
                    @foreach($user->todoItemsDone() as $item)
                        @if($item->status == 1)
                            <li>
                                {{ $item->title }}
                            </li>
                        @endif
                    @endforeach
                </ul>
            </div>

            <div class="col-md-6">
                <h3>User comments:</h3>
                <ul>
                    @foreach($user->comments as $comment)
                            <li>
                                Pakomentuota:
                                <a href="{{ route('todo.show', [$comment->todo_id]) }}">
                                    {{ $comment->todoItem->title }}
                                </a>
                                | {{ $comment->created_at->format('j F, Y') }}
                            </li>
                    @endforeach
                </ul>
            </div>
        </div>

    </div>

@endsection

blog/resources/views/users/task.blade.php
{{ $user->name }}

{{ $task->status }}