blog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/users', 'UserController@index')->name('users.index');

Route::get('/user/create', 'UserController@create')->name('users.create')->middleware('auth');
Route::post('/user/store', 'UserController@store')->name('users.store')->middleware('auth');

Route::get('/user/{id}', 'UserController@show')->name('users.show');
Route::get('/user/{id}/edit', 'UserController@edit')->name('users.edit')->middleware('auth');
Route::put('/user/{id}/update', 'UserController@update')->name('users.update')->middleware('auth');
Route::delete('/user/{id}/delete', 'UserController@delete')->name('users.delete')->middleware('auth');

Route::get('/user/{id}/tasks/{task_id}', 'UserController@showTask')->name('users.showTask');

Route::get('todo/completed', 'todoController@indexCompleted')->name('todo.indexCompleted');
Route::resource('todo', 'toDoController');
Route::post('todo/{id}/mark-as-completed', 'todoController@markAsCompleted')->name('todo.complete');

Route::resource('comment', 'CommentController');

blog/app/Http/Controllers/toDoController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use App\Http\Requests\StoreBlogPost;
use App\ToDoItem;
use App\User;
use Illuminate\Http\Request;

class toDoController extends Controller {
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index( Request $request ) {

		$order = "DESC";
		if ( $request->has( 'order' ) ) {
			$order = $request->input( 'order' );
		}

		$todoItems = ToDoItem::orderBy( 'created_at', $order )
							 ->get();

		$users = User::all();


		if ( $order == 'ASC' ) {
			$order = "DESC";
		} else {
			$order = "ASC";
		}


		return view( 'todo.index', [
			"todoItems" => $todoItems,
			"order" => $order,
			"users" => $users
		] );
	}

	public function indexCompleted( Request $request ) {
		$order = "DESC";
		if ( $request->has( 'order' ) ) {
			$order = $request->input( 'order' );
		}

		$todoItems = ToDoItem::where( [ [ 'status', 1 ], [ 'id', '<', 10 ] ] )
							 ->orWhere( 'status', 1 )
							 ->orderBy( 'created_at', $order )
							 ->get();


		$users = User::all();

		if ( $order == 'ASC' ) {
			$order = "DESC";
		} else {
			$order = "ASC";
		}


		return view( 'todo.index', [
			"todoItems" => $todoItems,
			"order" => $order,
			"users" => $users
		] );
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		//
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function store( StoreBlogPost $request ) {

		/* Patikriname savo uzklausa */
		$request->validated();

		// jei validatorius neatitiko taisykliu, tai sita dalis nebevykdoma

		//
		$todoItem          = new ToDoItem();
		$todoItem->title   = $request->input( 'title' );
		$todoItem->user_id = $request->input( 'user_id' );

		$todoItem->save();

		$request->session()->flash( 'message', 'Task was created successfuly!' );

		return redirect()->back();
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function show( $id ) {
		//
		$item = ToDoItem::find( $id );

		return view( 'todo.show', [ "item" => $item ] );
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit( $id ) {
		//
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function update( Request $request, $id ) {
		//

		$validatedData = $request->validate( [
			'title' => 'required|max:5',
			'user_id' => 'exists:users,id',
		] );
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function destroy( $id ) {
		//
		$todoItem = ToDoItem::find( $id );

		/*foreach($todoItem->comments as $comment) {
			$comment->delete();
		}*/

		if ( $todoItem->status == 1 ) {
			$todoItem->delete();
		}

		session()->flash( 'message', 'Task was deleted successfuly!' );
		session()->flash( 'message-class', 'alert-danger' );


		return redirect()->route( 'todo.index' );
	}

	public function markAsCompleted( $id ) {
		$todoItem         = ToDoItem::find( $id );
		$todoItem->status = 1;
		$todoItem->save();

		session()->flash( 'message', 'Task was completed successfuly!' );
		session()->flash( 'message-class', 'alert-success' );


		return redirect()->route( 'todo.index' );
	}
}

blog/resources/views/todo/components/comment-form.blade.php
<form method="post" action="{{ route('comment.store') }}">
    @csrf
    <div class="form-group">
        <textarea name="comment_text" class="form-control"></textarea>
    </div>

    <input type="hidden" name="todo_id" value="{{ $item->id }}">

    <input type="submit" value="Comment" class="btn btn-success">
</form>

blog/resources/views/todo/components/comments-list.blade.php
@if($item->comments->count() > 0)
    <h3>Comments: </h3>
    @foreach($item->comments as $comment)
        <div class="comment mt-3">
            Comment by:
            <a href="{{ route('users.show', [$comment->user->id]) }}">
                {{ $comment->user->name }}
            </a>

            <div>
                {{ $comment->comment_text }}
            </div>
            @if($comment->user_id == Auth::user()->id)
                <div>
                    <form action="{{ route('comment.destroy', [$comment->id]) }}" method="post">
                        @csrf
                        @method('delete')
                        <input type="submit" class="btn btn-danger" value="Delete comment">
                    </form>
                </div>
            @endif
        </div>
    @endforeach
@endif

blog/resources/views/todo/components/create.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<div class="form-group">
    <form method="post" action="{{ route('todo.store') }}">
        @csrf
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <input type="text" required name="title" class="form-control @error('title') is-invalid @enderror" value="{{ old('title') }}"
                           placeholder="Enter task title">
                    @error('title')
                    <div style="color: red;">{{ $message }}</div>
                    @enderror
                </div>
            </div>

            <div class="col-md-3">
                <select class="form-control @error('user_id') is-invalid @enderror" name="user_id" required>
                    <option value="">Pasirinkte vartotoja</option>
                    @foreach($users as $user)
                        @if($user->id == old('user_id'))
                            <option selected value="{{ $user->id }}">{{ $user->name }}</option>
                        @else
                            <option value="{{ $user->id }}">{{ $user->name }}</option>
                        @endif
                    @endforeach

                </select>
            </div>

            <div class="col-md-3">
                <input type="submit" value="Add task" class="btn-success btn btn-block">
            </div>
        </div>

    </form>
</div>